### ISSUE TITLE
Javascript router

### ISSUE THREAD

**Issue by onsails** [teamon/play-navigator#11]
Is it possible to use play-navigator with [`@helper.javascriptRouter`](http://www.playframework.com/documentation/2.1.1/ScalaJavascriptRouting).
When I try to use nav.\* inside `javascriptRouter` i see a compilation error:

``` Scala
@helper.javascriptRouter("jsRoutes")(
    nav.assets 
)
```

```
sbt.PlayExceptions$CompilationException: Compilation error[type mismatch;
 found   : controllers.nav.Route1[String]
 required: play.core.Router.JavascriptReverseRoute]
    at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15$$anonfun$apply$16.apply(PlayReloader.scala:349) ~[na:na]
    at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15$$anonfun$apply$16.apply(PlayReloader.scala:349) ~[na:na]
    at scala.Option.map(Option.scala:133) ~[scala-library.jar:na]
    at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15.apply(PlayReloader.scala:349) ~[na:na]
    at sbt.PlayReloader$$anon$2$$anonfun$reload$2$$anonfun$apply$15.apply(PlayReloader.scala:346) ~[na:na]
    at scala.Option.map(Option.scala:133) ~[scala-library.jar:na]
```

**Comment by teamon** [comment]
As you can see `@helper.javascriptRouter` requires `play.core.Router.JavascriptReverseRoute` which is currently not implemented in play-navigator. This shouldn't be complicated, but unfortunately I have no time for this right now. If you would like to help and implement this I'd more than grateful :)
